### ISSUE TITLE
无法加载登录验证码或二维码

### ISSUE THREAD

**Issue by ApolloLSY** [prcwcy/sjtu-canvas-video-download#10]
未挂代理 请问加载不出验证码和二维码有什么解决办法
![f553c68a710d823672e57b699daaa34](https://github.com/prcwcy/sjtu-canvas-video-download/assets/78656349/9bb24910-8910-44e1-a757-8572733140cd)
![da51dfca365f45c17576c116daffe9c](https://github.com/prcwcy/sjtu-canvas-video-download/assets/78656349/4a96e43c-cfbe-4e79-bbc9-a9e1355bcd86)
报错是
 ```
/sjtu-canvas-video-download/main.py
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\py\Python3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "d:\sjtu-canvas-video-download\sjtu_canvas_video_main_frame.py", line 192, in popup_login
    LoginFrame(
  File "d:\sjtu-canvas-video-download\sjtu_login_frame.py", line 126, in __init__
    self.refresh_all()
  File "d:\sjtu-canvas-video-download\sjtu_login_frame.py", line 139, in refresh_all
    self.params, self.uuid, self.cookies, self.url2 = get_params_uuid_cookies(
  File "d:\sjtu-canvas-video-download\sjtu_login.py", line 23, in get_params_uuid_cookies
    uuid = BeautifulSoup(
TypeError: 'NoneType' object is not subscriptable

```

**Comment by prcwcy** [comment]
这个问题应该已经在上个commit修复了, 参见 #9
