### ISSUE TITLE
无法使用过往课程ID下载

### ISSUE THREAD

**Issue by Li-Huanyu** [prcwcy/sjtu-canvas-video-download#11]
输入过往课程ID点击更新课程ID，报错如下：
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "sjtu_canvas_video_main_frame.py", line 256, in update_course_id
  File "sjtu_canvas_video_main_frame.py", line 184, in refresh_all_courses
  File "sjtu_real_canvas_video.py", line 81, in get_real_canvas_videos
  File "sjtu_real_canvas_video.py", line 19, in get_sub_cookies
AttributeError: 'NoneType' object has no attribute 'children'
```

**Comment by Li-Huanyu** [comment]
任何课程ID现在好像都无法正确解析了，在windows平台和ubuntu python运行源码都有相同的问题

**Comment by prcwcy** [comment]
已修复

**Comment by Li-Huanyu** [comment]
感谢，可以用了
