### ISSUE TITLE
Canvas系统更新导致获取二维码失败

### ISSUE THREAD

**Issue by SY-LG** [prcwcy/sjtu-canvas-video-download#8]
报错描述：打开软件，选择'登录jAccount（二维码）'，报错如下
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "sjtu_canvas_video_main_frame.py", line 244, in popup_qr_code_login
    QRCodeLoginFrame(
  File "sjtu_qr_code_login_frame.py", line 45, in __init__
    self.refresh_all()
  File "sjtu_qr_code_login_frame.py", line 78, in refresh_all
    self.params, self.uuid, self.cookies, self.url2 = get_params_uuid_cookies(
  File "sjtu_login.py", line 23, in get_params_uuid_cookies
    uuid = BeautifulSoup(
TypeError: 'NoneType' object is not subscriptable
```

怀疑是最近canvas系统更新导致的，校内社区也有关于Resnet验证码自动识别失效的讨论，发现问题为canvas更新后部分页面组件的名称发生变化

**Comment by SY-LG** [comment]
找到问题了，是uuid的标签变了，已提交PR
